#! /usr/bin/env sh

export LC_ALL
LC_ALL=C

proj="eix"
svnroot="https://svn.gentooexperimental.org/${proj}"

Usage () {
	printf '%s\n' "Usage: ${0##*/}
Marks a new release in the svn repository.
Verify in advance to have AC_INIT set correctly in configure.ac"
	exit ${1:-1}
}

Die () {
	printf '%s: %s\n' "${0##*/}" "${1}" >&2
	exit ${2:-1}
}

[ ${#} -eq 0 ] || Usage

ver="`sed -ne 's/^[[:space:]]*AC_INIT[[:space:]]*([^,]*,[[:space:][]*\([^],[:space:]]*\).*$/\1/p' configure.ac`"
printf '%s' "Are you sure you want to release ${proj}-${ver}? (y/n) "
while :
do	t="`stty -g`"
	stty -icanon -echo
	a="`dd count=1 bs=1 2>/dev/null`" || a=''
	stty ${t}
	case "${a}" in
	n*|N*)	printf '%s\n' "No"
		exit 1
		;;
	y*|Y*)	printf '%s\n' "Yes"
		break
		;;
	esac
done
printf '%s\n' "Creating release tag... "

svn copy "${svnroot}/trunk" "${svnroot}/tags/release-${ver}" \
	-m "Tagging the ${ver} release of the ${proj} project" >/dev/null || \
		die "svn copy failed"
