#! /bin/sh

export LC_ALL=C

proj="eix"
svnroot="https://svn.gentooexperimental.org/${proj}"

usage() {
	echo "Usage: mkrelease"
	echo "Verify in advance to have AC_INIT set correctly in configure.in"
}

die() {
	echo "$1"
	exit ${2:-1}
}

ver="`grep AC_INIT configure.in | awk '{ print $2 }'`"
ver=${ver%%,*}

ans=''
while [ -z "${ans}" ]; do
	read -p "Are you sure you want to release ${proj}-${ver}? (y/n) " ans
	case "${ans}" in
		n) echo "Not releasing anything"; exit 1;;
		y) ;;
		*) if [ -n "${ans}" ]; then
			echo "Unknown answer: ${ans}"
			exit 2
		fi;;
	esac
done
echo "Creating release tag... "

svn copy "${svnroot}/trunk ${svnroot}/tags/release-${ver}" \
	-m "Tagging the ${ver} release of the ${proj} project" >/dev/null || \
		die "svn copy failed"
