#! /usr/bin/env sh

export LC_ALL=C

die() {
	printf "%s\n" "${1}"
	exit ${2:-1}
}

if ! test -e Makefile
then
	test -e Makefile.in && test -e configure \
		|| ./autogen.sh || die "./autogen.sh failed"
	./configure || die "./configure failed"
fi
if test -e Makefile
then
	make maintainer-clean || die "make maintainer-clean failed"
fi
( cd po && make -f Rules-clean maintainer-clean-local )
for i in tar.lzma tar.bz2 tar.gz zip tar.Z shar.gz shar
do
	rm -vf -- eix-*."${i}"
done
find . '(' -name 'Makefile.in' -o -name 'svn-commit*.tmp' ')' -exec rm -v -- '{}' '+'
svn cleanup
