#! /bin/bash
die() {
	echo "$1"
	exit ${2:-1}
}

if ! [ -e Makefile ]; then
	[ -e Makefile.in ] && [ -e configure ] \
		|| ./autogen.sh || die "./autogen.sh failed"
	./configure || die "./configure failed"
fi
if [ -e Makefile ]; then
	make maintainer-clean || die "make maintainer-clean failed"
fi
rm -vrf build config
rm -vf aclocal.m4 configure config.h.in~
find -name "Makefile.in" -print0 | xargs -0 -r -- rm -v --
rm -i svn-commit*.tmp

