#! /bin/sh

export LC_ALL=C

usage() {
	echo "Usage: mktarball"
}

die() {
	echo "$1"
	exit ${2:-1}
}

test -d build || mkdir build >/dev/null
test -d build || die "cannot create directory build"

unset LDFLAGS CFLAGS CXXFLAGS
if command -v fakeroot >/dev/null 2>&1; then
	./mkmake -eqn || die "mkmake -qn failed"
	fakeroot ./mkmake -q dist || die "mkmake dist failed"
else
	./mkmake -eq dist || die "mkmake dist failed"
fi

for i in *.tar*; do
	md5sum "$i" >"$i.md5"
	mv "$i" "$i.md5" build
done

echo "Tarball is at build/"
echo "Note that to tag the release in svn you should run mkrelease"
