#! /usr/bin/env sh

export LC_ALL
LC_ALL=C
umask 022

Die() {
	s="${?}"
	printf '%s\n' "${1}" >&2
	exit ${2:-${s}}
}

ExecDie() {
	printf '# %s\n' "${*}"
	"${@}" || Die "${*} returned ${?}"
}

ExecDie git add .
ExecDie git commit -a
