#!/bin/bash

function to_classname () {
	echo -n ${1:0:1} | tr 'a-z' 'A-Z'
	echo "${1:1}Cache"
}

cache_names="backport cdb flat none metadata ebuild eixcache"
cache_stars="none ebuild"

cat<<END
// AUTOGENERATED BY MAKE .. DO NOT EDIT!
END

for cache_name in $cache_names; do
	cat<<END
#include "$cache_name/$cache_name.h"
END
done

cat<<END
using namespace std;

BasicCache *get_cache(string name) {
END

for cache_name in $cache_names; do
	cache_class=$(to_classname "$cache_name")
	[[ "$cache_name" != "eixcache" ]] && cat<<END
	if (name == "$cache_name") {
		return new $cache_class;
	}
END
done
for cache_name in $cache_stars; do
	cache_class=$(to_classname "$cache_name")
	[[ "$cache_name" != "eixcache" ]] && cat<<END
	if (name == "${cache_name}*") {
		return new $cache_class(true);
	}
END
done
cat<<END
	{
		EixCache *e=new EixCache;
		if(e->initialize(name))
			return e;
		delete e;
	}
	return NULL;
}
END
