#!/bin/sh

cat<<END
// AUTOGENERATED BY MAKE .. DO NOT EDIT!
END

for cache_name in *; do
	[ ! -d "$cache_name" ] && continue;
	cat<<END
#include "$cache_name/$cache_name.h"
END
done

cat<<END
using namespace std;

BasicCache *get_cache(string name) {
END

for cache_name in *; do
	[ ! -d "$cache_name" ] && continue;
	cache_class=$(echo "$cache_name" | sed 's,.,\U&,')Cache

	cat<<END
	if (name == "$cache_name") {
		return new $cache_class;
	}
END
done

cat<<END
	return NULL;
}
END
